##a=10
##b=2
##print('%d %d %d'%(a+b,a-b,a*b))
##a=(100+96+80)//3
##print('%d' %a)
##name=input('이름:')
##print('==자기 소개하기==')
##print('이름:%s'% name)
##name=input('이름:')
##age=input('나이:')
##height=input('키:')
##print('==자기 소개하기==')
##print('이름:%s'%name)
##print('나이:%s'%age)
##print('키:%s'%height)
##a=input()
##b=input()
##a=int(a)
##b=int(b)
##print('%d+%d=%d'% (a, b, a+b))
##play=input('경기종목:')
##grade=input('학년:')
##winner=input('이긴 반:')
##loser=input('진 반:')
##print('')
##print('================================================================')
##print('오늘 씨큐브 초등학교에서 %s 경기가 열렸습니다.' % play)
##print('%s%s과%s이 치열한 경기를 펼쳤고'%(grade, winner,loser))
##print('%s이 승리했습니다.'%winner)
##print('================================================================')
##y=input('연도:')
##m=input('월:')
##d=input('일:')
##print('오늘은 %s년 %월 %s일입니다.'(y.m.d))
